services:
  sonarqube:
    image: docker.io/library/sonarqube:25.7.0.110598-community
    depends_on:
      - pg_sonar
    env_file:
      - .env
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
    networks:
      - sonarqube
    ports:
      - "9000:9000"
  pg_sonar:
    # image: postgres:17.5
    image: docker.io/library/postgres:18
    env_file:
      - .env
    volumes:
      - pg_sonar:/var/lib/postgresql
    networks:
      - sonarqube
  # https://medium.com/@varun.thantry07/how-to-set-up-a-sonarqube-server-with-docker-compose-with-postgresql-and-elasticsearch-2d273ad93a3c
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    container_name: elasticsearch
    restart: always
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - es_sonar_data:/usr/share/elasticsearch/data

# echo "sonarqube_data sonarqube_extensions sonarqube_logs sonarqube_temp pg_sonar_config pg_sonar_data es_sonar_data" | xargs -n 1 podman volume create
volumes:
  sonarqube_data:
    external: true
  sonarqube_extensions:
    external: true
  sonarqube_logs:
    external: true
  sonarqube_temp:
    external: true
  pg_sonar:
    external: true
  es_sonar_data:
    external: true

# podman network create sonarqube
networks:
  sonarqube:
    external: true
