services:
  sonarqube:
    image: docker.io/library/sonarqube:25.7.0.110598-community
    restart: unless-stopped
    ports:
      # SonarQube UI
      - "9000:9000"
      # JMX exporter metrics
      - "9404:9404"
    depends_on:
      - pg_sonar
    env_file:
      - .env
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
    networks:
      - sonarqube
  pg_sonar:
    # image: postgres:17.5
    image: docker.io/library/postgres:18
    restart: unless-stopped
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${SONAR_POSTGRES_DB} -U ${SONAR_JDBC_USERNAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg_sonar:/var/lib/postgresql
    networks:
      - sonarqube
  # level=WARN source=main.go:85 msg="Error loading config" err="error opening config file \"postgres_exporter.yml\": open postgres_exporter.yml: no such file or directory"
  pg_sonar_exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # DATA_SOURCE_NAME: "postgresql://sonar:sonarpass@postgres:5432/sonarqube?sslmode=disable"
      DATA_SOURCE_NAME: "postgresql://${SONAR_JDBC_USERNAME}:${SONAR_JDBC_PASSWORD}@${SONAR_POSTGRES_HOST}:5432/${SONAR_POSTGRES_DB}?sslmode=disable"
    networks:
      - sonarqube
    depends_on:
      - pg_sonar
    ports:
      - "9187:9187"
  # https://github.com/prometheus/node_exporter
  # configuration: https://github.com/prometheus/exporter-toolkit/blob/master/docs/web-configuration.md
  # Local containers see this at: http://host.docker.internal:9100/metrics
  # You could see this at http://localhost:9100/metrics
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    restart: unless-stopped
    pid: "host"
    network_mode: "host"
    command:
      - --path.rootfs=/host
    volumes:
      - /:/host:ro,rslave
  # see if prometheus receives metrics on http://localhost:9099/targets
  prometheus:
    image: quay.io/prometheus/prometheus:latest
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:z,ro
      - prometheus:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
    ports:
      # Fedora: cockpit runs on 9090
      - "9099:9090"
    networks:
      - sonarqube
    depends_on:
      - sonarqube
      - pg_sonar_exporter
      - node-exporter
  grafana:
    image: docker.io/grafana/grafana-oss:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - grafana:/var/lib/grafana
    ports:
      # gaeko-ui runs on 3000
      - "3010:3000"
    networks:
      - sonarqube
    depends_on:
      - prometheus
  caddy:
    image: docker.io/library/caddy:2.10
    restart: unless-stopped
    env_file:
      - .env
    # cap_add:
    #   - NET_ADMIN
    ports:
      # - "80:80"
      # - "443:443"
      # - "443:443/udp"
      - "9001:9001"
      - "9002:9002"
      - "9002:9002/udp"
    volumes:
      - $PWD/caddy:/etc/caddy:z
      # - $PWD/site:/srv:z
      - caddy_data:/data
      - caddy_config:/config


# echo "sonarqube_data sonarqube_extensions sonarqube_logs sonarqube_temp pg_sonar_config pg_sonar_data es_sonar_data grafana prometheus" | xargs -n 1 podman volume create
volumes:
  sonarqube_data:
    external: true
  sonarqube_extensions:
    external: true
  sonarqube_logs:
    external: true
  sonarqube_temp:
    external: true
  pg_sonar:
    external: true
  grafana:
    external: true
  prometheus:
    external: true
  caddy_data:
    external: true
  caddy_config:
    external: true

# podman network create sonarqube
networks:
  sonarqube:
    external: true
