global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "sonarqube-jvm"
    metrics_path: /api/monitoring/metrics
    static_configs:
      # - targets: ["sonarqube:9000"]
      - targets: ["host.docker.internal:9000"]
  - job_name: "postgres"
    static_configs:
      - targets: ["pg_sonar_exporter:9187"]
  - job_name: "node"
    static_configs:
      - targets: ["host.docker.internal:9100"]  # node-exporter on host network

  # Add more jobs if you integrate cAdvisor or Podman-specific exporters
