global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "sonarqube-jvm-over-proxy"
    metrics_path: /api/monitoring/metrics
    static_configs:
      # - targets: ["host.docker.internal:9001"]
      - targets: ["caddy:9001"]
  - job_name: "sonarqube-jvm"
    metrics_path: /api/monitoring/metrics
    http_headers:
      X-Sonar-Passcode:
        # TODO: put pc from .env here
        values: ['my-secret-passcode']
    static_configs:
      - targets: ["sonarqube:9000"]
  - job_name: 'sonarqube-jmx'
    static_configs:
    - targets: ['sonarqube:9005']
  - job_name: "postgres"
    static_configs:
      - targets: ["pg_sonar_exporter:9187"]
  - job_name: "node"
    static_configs:
      - targets: ["host.docker.internal:9100"]  # node-exporter on host network
  - job_name: "my-podman-rootless"
    static_configs:
      - targets: ['podman-exporter:9882']
